Add --no-xattrs for yumdownloader
openshift/okd-machine-os pull request #107
Opened 2021-03-18 17:35 UTC by vrutkovs

This ensures RPMs are fetched without xattrs, as rpm-ostree 2020.2 no longer accepts those.

Ref: https://github.com/openshift/okd/issues/566#issuecomment-802147697

2021-03-18 17:43 UTC, cgwalters requested changes

2021-03-18 17:43 UTC, cgwalters commented on entrypoint.sh
> +YUMD_PARAMS="--no-xattrs --archlist=x86_64 --archlist=noarch --releasever=${VERSION_ID} ${REPOLIST}"
Ah sorry I meant "it'd be nice if that existed", it doesn't today.  I tested the workaround from https://github.com/openshift/okd/issues/566#issuecomment-802147697 locally, basically:

```
yumdownloader ...
for f in *.rpm; do attr=$(getfattr -m 'user.*' $f | grep -Ee '^user'); setfattr -x ${attr} $f; done
```

2021-03-18 19:05 UTC, cgwalters commented on entrypoint.sh
> +    if [ ! -z "$fattr" ]; then
```suggestion
    if [  -n "$fattr" ]; then
```

2021-03-18 19:05 UTC, cgwalters commented on entrypoint.sh
> +      [ ! -z ] && setfattr -x ${attr} $i
```suggestion
      setfattr -x "${attr}" $i
```

2021-03-18 19:05 UTC, cgwalters commented on entrypoint.sh
> +    if [ ! -z "$fattr" ]; then
(Cosmetic)

2021-03-18 19:07 UTC, cgwalters commented
I think the problem isn't this code though, it's this line: https://github.com/openshift/okd-machine-os/blob/1503953c0f9fd2718ecc138a792e75c1064f7312/entrypoint.sh#L126

AFAICS the RPMs here are being passed to `rpm2cpio`, so we're already implicitly stripping that problematic xattr.  It's the extension RPMs which are stored literally.

2021-03-18 19:10 UTC, vrutkovs commented
Right, I was stripping the wrong RPMs (bootstrap passes, so cpio strips those)

2021-03-18 20:03 UTC, vrutkovs commented
/retest
/test e2e-gcp

2021-03-18 21:23 UTC, cgwalters approved these changes

2021-03-18 23:04 UTC, vrutkovs commented
I must have messed up the installer, as even bootstrap can't be ssh'ed

/hold

2021-03-19 07:59 UTC, vrutkovs commented
/retest

2021-03-19 08:59 UTC, vrutkovs commented
Podman is being weird again:
```
[root@ip-10-0-14-10 core]# mkdir /run/mco-machine-os-content
[root@ip-10-0-14-10 core]# podman rm -f ostree-container-pivot-39235be7-671a-4a1e-94db-632a0ef26f47
8a5ea179c26be36bbfe3d0ce49a778e771c7974fccac8b4830590e592b555668
[root@ip-10-0-14-10 core]# podman create --net=none --annotation=org.openshift.machineconfigoperator.pivot=true --name ostree-container-pivot-39235be7-671a-4a1e-94db-632a0ef26f47 registry.build02.ci.openshift.org/ci-op-rbn70ig5/stable@sha256:cd7e27b77906bdabd883c728b40f8182918e3bcd9afc9ed8aebd814382709190
4b8daf5322a1c2e908e06358deb9fe1bba538e893570a85ad6ff93e0da0156a1
[root@ip-10-0-14-10 core]# podman cp 4b8daf5322a1c2e908e06358deb9fe1bba538e893570a85ad6ff93e0da0156a1:/ /run/mco-machine-os-content/os-content-064874529
[root@ip-10-0-14-10 core]# ls -la /run/mco-machine-os-content/os-content-064874529
ls: cannot access '/run/mco-machine-os-content/os-content-064874529': No such file or directory
[root@ip-10-0-14-10 core]# ls -la /run/mco-machine-os-content
total 0
drwxr-xr-x. 21 root root  500 Mar 19 08:58 .
drwxr-xr-x. 39 root root 1120 Mar 19 08:57 ..
lrwxrwxrwx.  1 root root    7 Apr 23  2020 bin -> usr/bin
...
[root@ip-10-0-14-10 core]# podman -v
podman version 3.0.1
[root@ip-10-0-14-10 core]# rpm -qa podman
podman-3.0.1-1.fc33.x86_64
[root@ip-10-0-14-10 core]# cat /etc/os-release 
NAME=Fedora
VERSION="33.20210301.3.1 (CoreOS)"

```

2021-03-28 07:38 UTC, vrutkovs commented
/retest

2021-03-29 15:50 UTC, LorbusChris commented
/retest

2021-03-29 16:32 UTC, vrutkovs commented
/override ci/prow/e2e-aws

```
fail [github.com/openshift/origin/test/extended/cli/explain.go:450]: Unexpected error:
    <*errors.errorString | 0xc00354ead0>: {
        s: "failed to explain [\"baremetalhosts\" \"--api-version=metal3.io/v1alpha1\"]: exit status 1",
    }
    failed to explain ["baremetalhosts" "--api-version=metal3.io/v1alpha1"]: exit status 1
occurred
```
caused by missing baremetal support is baremetal installer

2021-03-30 07:20 UTC, vrutkovs commented
/override ci/prow/e2e-aws-upgrade
/override ci/prow/e2e-aws 

Known issues

2021-03-30 07:20 UTC, vrutkovs commented
/hold cancel

2021-03-30 07:30 UTC, merged